baseURL: "https://jimbobbennett.io"
languageCode: "en-us"
title: "JimBobBennett"

Paginate: 3
# disqusShortname: gurusabarish
# googleAnalytics: G-DWJJVE27WD

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1
    
    - identifier: videos
      name: Videos
      title: Videos
      url: /videos
      weight: 2

    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "JimBobBennett"
  description: Blog posts, videos and more from Jim
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  theme:
    disableThemeToggle: true
    defaultTheme: "dark" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    title: "Hi, I'm Jim."
    subtitle: "I do developer advocacy"
    content: "Regional Cloud Advocate at Microsoft focusing on communities in the Pacific North West and the [Redmond Reactor](http://developer.microsoft.com/reactor). <br>Particularly excited by the Internet of Things and edge computing."
    image: /images/png/jim-portrait-circle.png
    socialNetworks:
      github: https://github.com/JimBobBennett
      linkedin: https://linkedin.com/in/JimBobBennett
      twitter: https://twitter.com/JimBobBennett
      instagram: https://instagram.com/JimBobBennett

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/jpg/jim-portrait-2-square.jpg"
    content: |-
      I am a Regional Cloud Advocate focusing on building out and skilling communities in the Pacific North West, with a focus on the Microsoft Reactor in Redmond, Washington, as well as a passion for the internet of things, edge computing and TinyML. I'm British, so I sound way smarter than I actually am.
      
      In the past I've lived in 4 continents working as a developer in the mobile, desktop, and scientific space. I've spoken at conferences and events all around the globe, organised meetup groups and communities, and written a book on mobile development.

      I also hate and am allergic to cats, but I have a 9-year-old daughter who loves cats, so I have 2 cats.
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "IoT"
        - "Edge computing"
        - "AI"
        - "TinyML"
        - "C++"
        - "Python"

  # projects
  projects:
    enable: true
    title: "Recent highlights"
    items:
      - title: IoT for Beginners
        content: 12 Weeks, 24 Lessons. IoT for All!
        image: https://raw.githubusercontent.com/microsoft/IoT-For-Beginners/main/images/iot-for-beginners.png
        featured:
          name: Get started
          link: https:/aka.ms/iot-beginners
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/Microsoft/iot-for-beginners
          - icon: fab fa-twitter
            url: https://twitter.com/intent/tweet?text=IoT+for+beginners!+Learn+IoT+with+24+free+lessons+from+@jimbobbennett+and+friends:&url=https%3A%2F%2Fgithub.com%2FMicrosoft%2FIoT-for-beginners

      - title: "Let's get personal: Computing"
        content: On-demand interview series with cool projects that you can build.
        image: /images/jpg/lets-get-personal-computing.jpg
        featured:
          name: Watch now
          link: https://youtube.com/playlist?list=PLlrxD0HtieHgv_WcR8HNQqrUPmJW9UybL
        # badges:
        #   - "Django"
        #   - "Bootstrap"
        links:
          - icon: fab fa-youtube
            url: https://youtube.com/playlist?list=PLlrxD0HtieHgv_WcR8HNQqrUPmJW9UybL
          - icon: fab fa-twitter
            url: https://twitter.com/intent/tweet?text=Let's+get+personal:+Computing.+Join+@JimBobBennett+as+he+interviews+guests+who+have+built+cool+projects+you+car+recreate+at+home.&url=https%3A%2F%2Fyoutube.com%2Fplaylist%3Flist=PLlrxD0HtieHgv_WcR8HNQqrUPmJW9UybL

      - title: "#JulyOT 2022"
        content: Celebrate 31 days of IoT!
        image: /images/gif/julyot.gif
        featured:
          name: Join the celebration
          link: https://JulyOT.dev
        links:
          - icon: fab fa-github
            url: https://github.com/JulyOT/JulyOT
          - icon: fab fa-twitter
            url: https://twitter.com/intent/tweet?text=%23JulyOT+is+here!+Celebrate+%23IoT+with+31+days+of+content.&url=https%3A%2F%2Fjulyot.dev

      - title: Xamarin in Action
        content: Create native cross-platform apps. Published by Manning Publications.
        image: /images/jpg/XamarinInActionFinal.jpg
        featured:
          name: Buy a copy
          link: https://www.manning.com/books/xamarin-in-action

  footer:
    # recentPosts: false
    socialNetworks:
      github: https://github.com/JimBobBennett
      linkedin: https://linkedin.com/in/JimBobBennett
      twitter: https://twitter.com/JimBobBennett
      instagram: https://instagram.com/JimBobBennett
