baseURL: "https://jimbobbennett.io"
languageCode: "en-us"
title: "JimBobBennett"

Paginate: 3
# disqusShortname: gurusabarish
# googleAnalytics: G-DWJJVE27WD

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1
    
    - identifier: videos
      name: Videos
      title: Videos
      url: /videos
      weight: 2
    
    - identifier: livestreams
      name: Livestreams
      title: Livestreams
      url: /livestreams
      weight: 3

    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "JimBobBennett"
  description: Blog posts, videos and more from Jim
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  theme:
    disableThemeToggle: true
    defaultTheme: "dark" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    title: "Hi, I'm Jim."
    subtitle: "I do developer advocacy"
    content: "Regional Cloud Advocate at Microsoft focusing on communities in the Pacific North West and the [Redmond Reactor](http://developer.microsoft.com/reactor). <br>Particularly excited by the Internet of Things and edge computing."
    image: /images/png/jim-portrait-circle.png
    socialNetworks:
      github: https://github.com/JimBobBennett
      linkedin: https://linkedin.com/in/JimBobBennett
      twitter: https://twitter.com/JimBobBennett
      instagram: https://instagram.com/JimBobBennett

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/jpg/jim-portrait-2-square.jpg"
    content: |-
      I am a Regional Cloud Advocate focusing on building out and skilling communities in the Pacific North West, with a focus on the Microsoft Reactor in Redmond, Washington, as well as a passion for the internet of things, edge computing and TinyML. I'm British, so I sound way smarter than I actually am.
      
      In the past I've lived in 4 continents working as a developer in the mobile, desktop, and scientific space. I've spoken at conferences and events all around the globe, organised meetup groups and communities, and written a book on mobile development.

      I also hate and am allergic to cats, but I have a 9-year-old daughter who loves cats, so I have 2 cats.
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "IoT"
        - "Edge computing"
        - "AI"
        - "TinyML"
        - "C++"
        - "Python"

  # projects
  projects:
    enable: true
    title: "Recent highlights"
    items:
      - title: IoT for Beginners
        content: 12 Weeks, 24 Lessons. IoT for All!
        image: https://raw.githubusercontent.com/microsoft/IoT-For-Beginners/main/images/iot-for-beginners.png
        featured:
          name: Get started
          link: https:/aka.ms/iot-beginners
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/Microsoft/iot-for-beginners
          - icon: fab fa-twitter
            url: https://twitter.com/intent/tweet?text=IoT+for+beginners!+Learn+IoT+with+24+free+lessons+from+@jimbobbennett+and+friends:&url=https%3A%2F%2Fgithub.com%2FMicrosoft%2FIoT-for-beginners

      - title: "Let's get personal: Computing"
        content: On-demand interview series with cool projects that you can build.
        image: /images/jpg/lets-get-personal-computing.jpg
        featured:
          name: Watch now
          link: https://youtube.com/playlist?list=PLlrxD0HtieHgv_WcR8HNQqrUPmJW9UybL
        # badges:
        #   - "Django"
        #   - "Bootstrap"
        links:
          - icon: fab fa-youtube
            url: https://youtube.com/playlist?list=PLlrxD0HtieHgv_WcR8HNQqrUPmJW9UybL
          - icon: fab fa-twitter
            url: https://twitter.com/intent/tweet?text=Let's+get+personal:+Computing.+Join+@JimBobBennett+as+he+interviews+guests+who+have+built+cool+projects+you+car+recreate+at+home.&url=https%3A%2F%2Fyoutube.com%2Fplaylist%3Flist=PLlrxD0HtieHgv_WcR8HNQqrUPmJW9UybL

      - title: "#JulyOT 2022"
        content: Celebrate 31 days of IoT!
        image: /images/gif/julyot.gif
        featured:
          name: Join the celebration
          link: https://JulyOT.dev
        links:
          - icon: fab fa-github
            url: https://github.com/JulyOT/JulyOT
          - icon: fab fa-twitter
            url: https://twitter.com/intent/tweet?text=%23JulyOT+is+here!+Celebrate+%23IoT+with+31+days+of+content.&url=https%3A%2F%2Fjulyot.dev

      - title: Xamarin in Action
        content: Create native cross-platform apps. Published by Manning Publications.
        image: /images/jpg/XamarinInActionFinal.jpg
        featured:
          name: Buy a copy
          link: https://www.manning.com/books/xamarin-in-action

  footer:
    # recentPosts: false
    socialNetworks:
      github: https://github.com/JimBobBennett
      linkedin: https://linkedin.com/in/JimBobBennett
      twitter: https://twitter.com/JimBobBennett
      instagram: https://instagram.com/JimBobBennett
  
  videos:
    series:
    - title: "Let's get personal: Computing"
      videos:
      - title: "Build your own pocket sized Altair 8800!"
        id: 2yyBfw3CARc
        description: Take a trip down memory lane with the Altair 8800, the microcomputer that sparked the personal computing revolution. Learn how to build your own pocket-sized Altair with Dave Glover, Sr Technologist at Microsoft. 
        
      - title: "Build a bionic hand using open source prosthetics"
        id: 60XyevlK2GI
        description: On today’s show, Jim is joined by Cliff Agius, a pilot and IoT and mobile developer from the UK. He’s mixed the power of 3D modeling software, consumer 3D printers, low priced IoT hardware and a mobile app to build an open source bionic hand that can be customized for a range of tasks, from picking things up, to playing Xbox.
        
      - title: "Build an IoT solution in under 5 minutes!"
        id: XPK3RUUPbjA
        description: On today’s show, Jim is joined by Vanessa, an IoT program manager from Microsoft, who's reduced the journey to IoT Wow to less than 5 minutes for some of the most popular developer kits from the manufacturers of the hardware you find in today's production IoT deployments.

    - title: "IoT Show"
      videos:
      - title: "IoT for Beginners"
        id: bccEMm8gRuc
        description: Jim Bennett joins Olivier to tell us all about IoT for beginners, a new 12 week, 24 lesson curriculum that we have built to get University and high school students ready for the fast-growing world of IoT.

      - title: "IoT for Beginners: Wio Terminal Hackathon - Part 1"
        id: a22_1ZRejfw
        description: "During this event, you will be introduced to the Internet of Things, and learn the basic concepts including building your first WioTerminal IoT project connecting to the cloud. Find out what Microsoft employees will be hacking for the annual Hackathon event later in October. Get a peek behind the curtain and stay after the event for Ask the Expert: IoT and WioTerminal Hackathon to get your questions answered from IoT experts."

      - title: "IoT for Beginners: Wio Terminal Hackathon - Part 2"
        id: iKqYoOVTHLs
        description: "During this event, you will be introduced to the Internet of Things, and learn the basic concepts including building your first WioTerminal IoT project connecting to the cloud. Find out what Microsoft employees will be hacking for the annual Hackathon event later in October. Get a peek behind the curtain and stay after the event for Ask the Expert: IoT and WioTerminal Hackathon to get your questions answered from IoT experts."

      - title: "IoT for Beginners: Wio Terminal Hackathon - Part 3"
        id: goiwqlDwR30
        description: "During this event, you will be introduced to the Internet of Things, and learn the basic concepts including building your first WioTerminal IoT project connecting to the cloud. Find out what Microsoft employees will be hacking for the annual Hackathon event later in October. Get a peek behind the curtain and stay after the event for Ask the Expert: IoT and WioTerminal Hackathon to get your questions answered from IoT experts."

      - title: "IoT is Fun for Everyone! (Ugly Sweater Edition)"
        id: KiG7kR95hIQ
        description: An Ugly Sweater is great—but what's even better is an IoT-enabled Ugly Sweater. In this episode of the IoT Show, Olivier Bloch is joined by Jim Bennett, a Senior Cloud Advocate at Microsoft. Jim has built an Ugly Sweater using Azure IoT Central, Microsoft's IoT app platform, and a Raspberry Pi Zero. Dive into Jim's Python code and learn how Azure IoT Central is able to connect IoT devices to the cloud faster than any other platform. See how Jim uses IoT Central's extensibility APIs to control his Ugly Sweater via Twitter. This code is on GitHub for you to play with and extend. Get started today!

      - title: "Geofencing with Azure Maps"
        id: nsrgYhaYNVY
        description: Join Jim Bennett, Azure Cloud Advocate, to learn how to code geofencing applications with Visual Studio, Python, and Azure Maps.

    - title: "The Xamarin Show"
      videos:
      - title: "Custom Vision 1 – Machine Learning Made Easy"
        id: TETcDLJlWR4
        description: This week James is joined by friend of the show Jim Bennett, a Cloud Developer Advocate at Microsoft, who shows us how to use AI inside a mobile app to identify his daughters’ toys. He walks through using the Azure custom vision service to generate a model to identify different toys, then shows how you can use these models from inside your app, both remotely by calling an Azure service, or locally by running the model on your device using CoreML and Tensorflow.
        
      - title: "Custom Vision 2 - Object Detection Made Easy "
        id: wtTYSyBUpFc
        description: In this show Jim looks at Custom Vision object detection. The custom vision service recently has been updated to include object detection, and this allows you to train the service to detect multiple objects inside an image with their locations, instead of just being a simple classifier. Jim walks through creating an object detection model, tagging regions in images that show the objects to be detected, then he builds a simple Xamarin app to use this to annotate a picture from his daughters toybox, naming all the toys it finds.

  livestreams:
    upcoming:
      series:
      - title: "Tech Career Tips - Sea of Nerds"
        videos:
          - title: Tech career tips from educators
            description: "Arrrrrrr, ye swarthy land lubbers. Come set sail with your pirate captain, the Dread Pirate Jim and his pirate crew as we set sail on the seven seas to find the finest treasure in the land – knowledge!"
            image: /images/livestreams/sea-of-nerds-4.jpeg
            registrationLink: https://developer.microsoft.com/reactor/events/16698/

    previous:
      series:
      - title: "Tech Career Tips - Sea of Nerds"
        videos:
          - title: "Tech career tips from educators at Microsoft – Sea of Nerds"
            id: Z6I8227-Br8
            description: For this session, our crew is joined by Jennifer Ritzinger, the General Manager of the Next Generation Experiences team at Microsoft, and Pablo Veramendi, director of audience evangelism and the brains behind the Microsoft Learn Student Ambassador and Imagine Cup programs.
          - title: "Tech career tips from graduate hires at Microsoft – Sea of Nerds"
            id: 1PuP6JHxtwA
            description: For this session, our crew is joined by a couple of young pirates who interned at Microsoft in different ways before taking graduate roles with the company. Tessa Wiedmann started as an engineer, but being a former Student Ambassador jumped at the chance to help grow this program! Gustavo Cordido joined under more locked down circumstances, doing a virtual internship at the start of the pandemic. That experience didn’t put him off a life on the ocean waves, and he joined Microsoft as a developer advocate when he graduated.
          - title: "Tech career tips from interns at Microsoft – Sea of Nerds"
            id: An5lBy_zTe0
            description: For this session, our crew is joined by a group of young pirates who recently interned at Microsoft.
      - title: "IoT for Beginners"
        videos:
          - title: "Lesson 1: Introduction to IoT"
            id: bVFfcYh6UBw
            description: This lesson covers some of the introductory topics around the Internet of Things, and shows a basic ‘Hello World’ project with a microcontroller.
          - title: "Lesson 1: Introduction to IoT office hours"
            id: YI772q5v3yI
            description: As a follow up to what was covered in the last ‘IoT for beginners’ session, join Jim for an open office hour where you can ask questions relating to the material that has been covered in the series so far, getting explanations of the concepts taught, diving deeper into theory or practice, or getting troubleshooting help on your IoT journey.
          - title: "Lesson 2: A Deeper Dive into IoT"
            id: bVFfcYh6UBw
            description: This lesson dives deeper into some of the concepts covered in the last lesson. The two components of an IoT application are the Internet and the thing, and this lesson dives deeper into both of these, covering different types of ‘things’, including microcontrollers and single-board computers. It then looks at the  different ways these ‘things’ can use the Internet.
          - title: "Lesson 2: A Deeper Dive into IoT office hours"
            id: YI772q5v3yI
            description: As a follow up to what was covered in the last ‘Introduction to dev kit hardware’ session, join Jim for an open office hour where you can ask questions relating to the material that has been covered in the series so far, getting explanations of the concepts taught, diving deeper into theory or practice, or getting troubleshooting help on your IoT journey.
          - title: "Lesson 3: Interact with the Physical World with Sensors and Actuators"
            id: Lqalu1v6aF4
            description: This lesson introduces two of the important concepts for your IoT device - sensors and actuators. Sensors read data from the physical world, actuators control it, and this lesson looks in more depth at how this happens, covering analog and digital hardware (and what these terms mean). You will also see how to build a nightlight with a microcontroller, using sensor data to control an actuator.
          - title: "Lesson 3: Interact with the Physical World with Sensors and Actuators office hours"
            id: qR3ekcMlLWA
            description: As a follow up to what was covered in the last ‘ Interacting with the Physical World with sensors and Actuators’ session, join Jim for an open office hour where you can ask questions relating to the material that has been covered in the series so far, getting explanations of the concepts taught, diving deeper into theory or practice, or getting troubleshooting help on your IoT journey.
          - title: "Lesson 4: Connect your Device to the Internet"
            id: O4dd172mZhs
            description: This lesson introduces some of the communication protocols IoT devices can use to connect to the cloud, and the types of data they might send or receive. It will also show how to control a microcontroller over MQTT.
          - title: "Lesson 4: Connect your Device to the Internet office hours"
            id: j-cVCzRDE2Q
            description: As a follow up to what was covered in the last ‘Communicating with Devices’ session, join Jim for an open office hour where you can ask questions relating to the material that has been covered in the series so far, getting explanations of the concepts taught, diving deeper into theory or practice, or getting troubleshooting help on your IoT journey.
